# Offense count: 231
# Configuration parameters: Prefixes, AllowedPatterns.
# Prefixes: when, with, without
RSpec/ContextWording:
  Enabled: false

# Offense count: 32
# Configuration parameters: IgnoredMetadata.
RSpec/DescribeClass:
  Enabled: false

# Offense count: 16
# Configuration parameters: CountAsOne.
RSpec/ExampleLength:
  Max: 86

RSpec/NamedSubject:
  Enabled: false

# Offense count: 4
RSpec/RepeatedExampleGroupBody:
  Exclude:
    - 'spec/defines/config/server/realm_spec.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: implicit, explicit
Style/RescueStandardError:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 253
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyleForMultiline.
# SupportedStylesForMultiline: comma, consistent_comma, no_comma
Style/TrailingCommaInHashLiteral:
  Enabled: false
