# Offense count: 231
# Configuration parameters: Prefixes, AllowedPatterns.
# Prefixes: when, with, without
RSpec/ContextWording:
  Enabled: false

# Offense count: 32
# Configuration parameters: IgnoredMetadata.
RSpec/DescribeClass:
  Enabled: false

# Offense count: 16
# Configuration parameters: CountAsOne.
RSpec/ExampleLength:
  Max: 86

RSpec/NamedSubject:
  Enabled: false

# Offense count: 4
# RSpec/MultipleExpectations:
#   Max: 2

# Offense count: 30
# Configuration parameters: AllowedPatterns.
# AllowedPatterns: ^expect_, ^assert_
RSpec/NoExpectationExample:
  Exclude:
    - 'spec/acceptance/acceptance_1_readme_spec.rb'
    - 'spec/acceptance/acceptance_1b_spec.rb'
    - 'spec/acceptance/acceptance_2b_spec.rb'
    - 'spec/acceptance/acceptance_3b_spec.rb'
    - 'spec/acceptance/acceptance_4b_spec.rb'

# Offense count: 4
RSpec/RepeatedExampleGroupBody:
  Exclude:
    - 'spec/defines/config/server/realm_spec.rb'

# Offense count: 1
Style/MixinUsage:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 22
# This cop supports safe autocorrection (--autocorrect).
Style/RedundantRegexpEscape:
  Exclude:
    - 'spec/acceptance/acceptance_3b_spec.rb'
    - 'spec/acceptance/acceptance_4b_spec.rb'
    - 'spec/defines/setenv/entry_spec.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: implicit, explicit
Style/RescueStandardError:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 253
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyleForMultiline.
# SupportedStylesForMultiline: comma, consistent_comma, no_comma
Style/TrailingCommaInHashLiteral:
  Enabled: false
