# Offense count: 167
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowMultipleStyles, EnforcedHashRocketStyle, EnforcedColonStyle, EnforcedLastArgumentHashStyle.
# SupportedHashRocketStyles: key, separator, table
# SupportedColonStyles: key, separator, table
# SupportedLastArgumentHashStyles: always_inspect, always_ignore, ignore_implicit, ignore_explicit
# Layout/HashAlignment:
#   Enabled: false

# Offense count: 15
# This cop supports safe autocorrection (--autocorrect).
# Layout/SpaceAroundMethodCallOperator:
#   Exclude:
#     - 'spec/defines/config/server/context_spec.rb'
#     - 'spec/defines/config/server/listener_spec.rb'
#     - 'spec/defines/config/server/realm_spec.rb'
#     - 'spec/defines/config/server/resources_spec.rb'
#     - 'spec/defines/config/server/tomcat_users_spec.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyleForEmptyBraces.
# SupportedStyles: space, no_space, compact
# SupportedStylesForEmptyBraces: space, no_space
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

# Offense count: 1
# Configuration parameters: AllowComments, AllowEmptyLambdas.
Lint/EmptyBlock:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 1
# Configuration parameters: ForbiddenDelimiters.
# ForbiddenDelimiters: (?i-mx:(^|\s)(EO[A-Z]{1}|END)(\s|$))
Naming/HeredocDelimiterNaming:
  Exclude:
    - 'spec/defines/config/server/realm_spec.rb'

# Offense count: 231
# Configuration parameters: Prefixes, AllowedPatterns.
# Prefixes: when, with, without
RSpec/ContextWording:
  Enabled: false

# Offense count: 32
# Configuration parameters: IgnoredMetadata.
RSpec/DescribeClass:
  Enabled: false

# Offense count: 67
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowConsecutiveOneLiners.
RSpec/EmptyLineAfterExample:
  Exclude:
    - 'spec/acceptance/acceptance_1_readme_spec.rb'
    - 'spec/acceptance/acceptance_1b_spec.rb'
    - 'spec/acceptance/acceptance_2b_spec.rb'
    - 'spec/acceptance/acceptance_3b_spec.rb'
    - 'spec/acceptance/acceptance_4b_spec.rb'
    - 'spec/defines/config/server/realm_spec.rb'
    - 'spec/defines/config/server/service_spec.rb'
    - 'spec/defines/config/server/tomcat_users_spec.rb'
    - 'spec/defines/instance_spec.rb'
    - 'spec/defines/setenv/entry_spec.rb'
    - 'spec/defines/war_spec.rb'

# Offense count: 167
# This cop supports safe autocorrection (--autocorrect).
RSpec/EmptyLineAfterExampleGroup:
  Enabled: false

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowConsecutiveOneLiners.
RSpec/EmptyLineAfterHook:
  Exclude:
    - 'spec/acceptance/acceptance_1_readme_spec.rb'

# Offense count: 16
# Configuration parameters: CountAsOne.
RSpec/ExampleLength:
  Max: 86

# Offense count: 128
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: single_line_only, single_statement_only, disallow, require_implicit
RSpec/ImplicitSubject:
  Enabled: false

# Offense count: 4
RSpec/MultipleExpectations:
  Max: 2

# Offense count: 30
# Configuration parameters: AllowedPatterns.
# AllowedPatterns: ^expect_, ^assert_
RSpec/NoExpectationExample:
  Exclude:
    - 'spec/acceptance/acceptance_1_readme_spec.rb'
    - 'spec/acceptance/acceptance_1b_spec.rb'
    - 'spec/acceptance/acceptance_2b_spec.rb'
    - 'spec/acceptance/acceptance_3b_spec.rb'
    - 'spec/acceptance/acceptance_4b_spec.rb'

# Offense count: 4
RSpec/RepeatedExampleGroupBody:
  Exclude:
    - 'spec/defines/config/server/realm_spec.rb'

# Offense count: 1
Style/MixinUsage:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 22
# This cop supports safe autocorrection (--autocorrect).
Style/RedundantRegexpEscape:
  Exclude:
    - 'spec/acceptance/acceptance_3b_spec.rb'
    - 'spec/acceptance/acceptance_4b_spec.rb'
    - 'spec/defines/setenv/entry_spec.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: implicit, explicit
Style/RescueStandardError:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 253
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyleForMultiline.
# SupportedStylesForMultiline: comma, consistent_comma, no_comma
Style/TrailingCommaInHashLiteral:
  Enabled: false
